# ENGR421 HW2 

# Özge Sayar

In [176]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.stats as stats

def safelog(x):
    return(np.log(x + 1e-100))

## Importing Data

In [177]:
dataset_images = np.genfromtxt('hw02_data_set_images.csv',delimiter=',').reshape(5, 39, 320)
dataset_labels = np.char.strip(np.genfromtxt('hw02_data_set_labels.csv',delimiter=',',dtype=str),'"').reshape(5,39)

dataset_labels = dataset_labels.astype(int)

## Train and Test Data 

In [193]:
#define train data (25 x 5)
trainingdata_images = dataset_images[:,:25,:].reshape(125, 320)
trainingdata_labels = dataset_labels[:,:25].reshape(125,)
    
#define test data (14 x 5)
testdata_images = dataset_images[:,25:,:].reshape(70, 320)
testdata_labels = dataset_labels[:,25:].reshape(70,)

print(trainingdata_images)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## Estimating Parameters

In [194]:
# calculate pcd
N_train = 125
pcd = np.zeros((K, 320))
#for i in range (len(trainingdata_images)):
#    pcd = np.array([np.sum(np.dot(trainingdata_labels[i] == (c + 1), trainingdata_images[i]) for c in range(N_train))])/np.array([np.sum(trainingdata_labels == (c + 1)) for c in range(N_train)])

for c in range(K):
    for p in range(320):
        pcd[c][p] = (np.sum(trainingdata_images[n][p] for n in range(int(c*N_train/K), int((c+1)*N_train/K))) / (N_train/K))

# calculate prior probabilities
class_priors = [np.mean(trainingdata_labels == (c + 1)) for c in range(K)]

print(pcd)
print(class_priors)

[[0.   0.   0.   ... 0.68 0.68 0.64]
 [0.04 0.24 0.24 ... 0.8  0.56 0.24]
 [0.   0.   0.   ... 0.6  0.88 0.8 ]
 [0.12 0.44 0.4  ... 0.28 0.16 0.08]
 [0.   0.12 0.12 ... 0.32 0.48 0.44]]
[0.2, 0.2, 0.2, 0.2, 0.2]


C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  if __name__ == '__main__':


### Score Function

In [205]:
#Score function
Score= np.zeros((125,5))

for n in range (125):
    for c in range (5):
        for p in range(320):
            Score[n][c] += np.sum(np.dot(trainingdata_images[p],safelog(pcd[c][p])) 
                                    + np.dot((1-trainingdata_images[p]),safelog(1-pcd[c][p]))
                                            + safelog(class_priors[c])) 
            Scores= np.append(Score[n][c])
            
Scores= np.array(Scores)

TypeError: append() missing 1 required positional argument: 'values'

## Confusion Matrix for Train Data

In [196]:
#Scores for Train
for n in range (125): 
    TrainScores = np.argmax(Score[n][c] for c in range (5))
    
ConfusionMatrix_train = pd.crosstab(TrainScores, trainingdata_labels, 
                                     rownames = ["y_pred"], 
                                     colnames = ["y_truth"])
print(ConfusionMatrix_train)

ValueError: arrays must all be same length

## Confusion Matrix for Test Data 

In [197]:
for n in range (125):
    TestScores = np.argmax(Score[n][c] for c in range (5))

ConfusionMatrix_test = pd.crosstab(TestScores, testdata_labels, 
                                     rownames = ["y_pred"], 
                                     colnames = ["y_truth"])
print(ConfusionMatrix_test)

ValueError: arrays must all be same length